'''
This client helps you to download the files generated by monitor.sh

In previous versions there were sent by email. It will be fixed on future version.

The files will be transferred using our local network. Our Raspberry Pi require to get Python3 installed on Raspberry OS and the port you
wish to use to transfer it must be allowed by the firecall to avoid any possible issue trying to connect to our RaspPi.

The file will be download to the same directory that this source is execute.

'''

import urllib.request, urllib.error, urllib.parse
import os

def checker(IP): #Check if your server is available or not
    check = os.system("ping -c 1 " + IP + "> /dev/null 2>&1")
    value = 0
    if check == 0 : 
        #print("%s available" % IP)
        value = 0
    else:
        #print("%s not available" % hostname)
        value = 1
    return value

if __name__ == '__main__':

    hostname = "123.456.7.89" #change here your IP
    if checker(hostname) == 0:
        Files = ['temperature.txt','ports.txt','process.txt','hosts.txt'] #Files generated by monitor.sh
        Port = '8080' #This can be changed, more info on the previous paragraph
        IP = 'your_Raspberry_Pi_IP' #IP of your Raspberry Pi
    
        for i in range(len(Files)):
            url = 'http://'+ str(IP)+ ':' + str(Port) + '/' + str(Files[i])
            response = urllib.request.urlopen(url)
            content = response.read()
            theFile = open(str(Files[i]),'wb')
            theFile.write(content)
            theFile.close()
