'''
This client helps you to download the files generated by monitor.sh

The files will be transferred using our local network. Our Raspberry Pi require to get Python3 installed on Raspberry OS and the port you
wish to use to transfer it must be allowed by the firecall to avoid any possible issue trying to connect to our RaspPi.

Do not forget to edit the file "parameters.txt" on config folder. This file contains the IP and port used by the client.
format:
    <IP> <port>


The files will be downloaded to the same directory that this source is execute.

'''

import urllib.request, urllib.error, urllib.parse
import os

def checker(IP): #Check if your server is available or not
    check = os.system("ping -c 1 " + IP + "> /dev/null 2>&1")
    value = 0
    if check == 0 : 
        value = 0
    else:
        value = 1
    return value

if __name__ == '__main__':
    with open("config/parameters.txt", "r") as f:
        linea = f.read().split(" ")
        linea[1] = linea[1].split("\n")
        linea[1] = linea[1][0]    
    IP = linea[0]
    if checker(IP) == 0:
        Files = ['temperature.txt','ports.txt','process.txt','hosts.txt'] #Files generated by monitor.sh
        Port = linea[1]

    
        for i in range(len(Files)):
            url = 'http://'+ str(IP)+ ':' + str(Port) + '/' + str(Files[i])
            response = urllib.request.urlopen(url)
            content = response.read()
            theFile = open(str(Files[i]),'wb')
            theFile.write(content)
            theFile.close()
