'''
This client helps you to download the files generated by monitor.sh

In previous versions there were sent by email. It will be fixed on future version.

The files will be transferred using our local network. Our Raspberry Pi require to get Python3 installed on Raspberry OS and the port you
wish to use to transfer it must be allowed by the firecall to avoid any possible issue trying to connect to our RaspPi.

The file will be download to the same directory that this source is execute.

'''



import urllib.request, urllib.error, urllib.parse

Files = ['temperature.txt','ports.txt','process.txt','hosts.txt'] #Files generated by monitor.sh
Port = '8080' #This can be changed, more info on the previous paragraph
IP = 'your_Raspberry_Pi_IP' #IP of your Raspberry Pi

for i in range(len(Files)):
    url = 'http://'+ str(IP)+ ':' + str(Port) + '/' + str(Files[i])
    response = urllib.request.urlopen(url)
    content = response.read()
    theFile = open(str(Files[i]),'wb')
    theFile.write(content)
    theFile.close()
